package com.ourshop.mapper;

import java.util.List;

import com.ourshop.model.Od;
import com.ourshop.model.OdExample;
import com.ourshop.model.OdKey;
import org.apache.ibatis.annotations.Param;


public interface OdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int countByExample(OdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int deleteByExample(OdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OdKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int insert(Od record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int insertSelective(Od record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    List<Od> selectByExample(OdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    Od selectByPrimaryKey(OdKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Od record, @Param("example") OdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Od record, @Param("example") OdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Od record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Od record);
}