package com.ourshop.model;

public class Cart extends CartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.num
     *
     * @return the value of cart.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.num
     *
     * @param num the value for cart.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}