package com.ourshop.model;

public class CartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.gID
     *
     * @mbggenerated
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.gID
     *
     * @return the value of cart.gID
     *
     * @mbggenerated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.gID
     *
     * @param gid the value for cart.gID
     *
     * @mbggenerated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.uid
     *
     * @return the value of cart.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.uid
     *
     * @param uid the value for cart.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}