package com.ourshop.model;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gID
     *
     * @mbggenerated
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.tagID
     *
     * @mbggenerated
     */
    private Integer tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.fimageURL
     *
     * @mbggenerated
     */
    private String fimageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gName
     *
     * @mbggenerated
     */
    private String gname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.dis
     *
     * @mbggenerated
     */
    private String dis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gID
     *
     * @return the value of goods.gID
     *
     * @mbggenerated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gID
     *
     * @param gid the value for goods.gID
     *
     * @mbggenerated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.tagID
     *
     * @return the value of goods.tagID
     *
     * @mbggenerated
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.tagID
     *
     * @param tagid the value for goods.tagID
     *
     * @mbggenerated
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.fimageURL
     *
     * @return the value of goods.fimageURL
     *
     * @mbggenerated
     */
    public String getFimageurl() {
        return fimageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.fimageURL
     *
     * @param fimageurl the value for goods.fimageURL
     *
     * @mbggenerated
     */
    public void setFimageurl(String fimageurl) {
        this.fimageurl = fimageurl == null ? null : fimageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.stock
     *
     * @return the value of goods.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.stock
     *
     * @param stock the value for goods.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gName
     *
     * @return the value of goods.gName
     *
     * @mbggenerated
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gName
     *
     * @param gname the value for goods.gName
     *
     * @mbggenerated
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.dis
     *
     * @return the value of goods.dis
     *
     * @mbggenerated
     */
    public String getDis() {
        return dis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.dis
     *
     * @param dis the value for goods.dis
     *
     * @mbggenerated
     */
    public void setDis(String dis) {
        this.dis = dis == null ? null : dis.trim();
    }
}