package com.ourshop.model;

public class Od extends OdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od.gNum
     *
     * @mbggenerated
     */
    private Integer gnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od.gNum
     *
     * @return the value of od.gNum
     *
     * @mbggenerated
     */
    public Integer getGnum() {
        return gnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od.gNum
     *
     * @param gnum the value for od.gNum
     *
     * @mbggenerated
     */
    public void setGnum(Integer gnum) {
        this.gnum = gnum;
    }
}