package com.ourshop.model;

public class Oder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.OID
     *
     * @mbggenerated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.adressID
     *
     * @mbggenerated
     */
    private Integer adressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oder.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.OID
     *
     * @return the value of oder.OID
     *
     * @mbggenerated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.OID
     *
     * @param oid the value for oder.OID
     *
     * @mbggenerated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.uid
     *
     * @return the value of oder.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.uid
     *
     * @param uid the value for oder.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.adressID
     *
     * @return the value of oder.adressID
     *
     * @mbggenerated
     */
    public Integer getAdressid() {
        return adressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.adressID
     *
     * @param adressid the value for oder.adressID
     *
     * @mbggenerated
     */
    public void setAdressid(Integer adressid) {
        this.adressid = adressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oder.state
     *
     * @return the value of oder.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oder.state
     *
     * @param state the value for oder.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}