package com.ourshop.model;

public class OdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od.OID
     *
     * @mbggenerated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od.gID
     *
     * @mbggenerated
     */
    private Integer gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od.OID
     *
     * @return the value of od.OID
     *
     * @mbggenerated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od.OID
     *
     * @param oid the value for od.OID
     *
     * @mbggenerated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od.gID
     *
     * @return the value of od.gID
     *
     * @mbggenerated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od.gID
     *
     * @param gid the value for od.gID
     *
     * @mbggenerated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }
}