package com.ourshop.model;

public class Tags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.tagID
     *
     * @mbggenerated
     */
    private Integer tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.tagName
     *
     * @mbggenerated
     */
    private String tagname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.tagID
     *
     * @return the value of tags.tagID
     *
     * @mbggenerated
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.tagID
     *
     * @param tagid the value for tags.tagID
     *
     * @mbggenerated
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.tagName
     *
     * @return the value of tags.tagName
     *
     * @mbggenerated
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.tagName
     *
     * @param tagname the value for tags.tagName
     *
     * @mbggenerated
     */
    public void setTagname(String tagname) {
        this.tagname = tagname == null ? null : tagname.trim();
    }
}